/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '25/10/16 8:39 PM' with Gradle 2.13
 *
 * @author hongkailiu, @date 25/10/16 8:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
